server {
    listen 80;
    server_name www.elmarhepp.de;
    return 301 https://elmarhepp.de$request_uri;
}

server {
    listen 80;
    server_name elmarhepp.de;
    return 301 https://elmarhepp.de$request_uri;
}

server {
    listen 443 ssl;
    server_name www.elmarhepp.de;

    ssl_certificate /etc/letsencrypt/live/elmarhepp.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/elmarhepp.de/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://elmarhepp.de$request_uri;
}

server {
    listen 443 ssl;
    server_name elmarhepp.de;

    root /var/www/elmarhepp-root;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/elmarhepp.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/elmarhepp.de/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
